"""
Meta-interview runner — the 8-turn hardcoded interview that elicits a DomainConfig.

Loads question bank from app/meta/meta_questions.json (generated by Opus).
Questions are asked verbatim in order; no orchestration, no branching.
"""
from __future__ import annotations

import inspect
import json
from pathlib import Path
from typing import Awaitable, Callable, Union

from pydantic import BaseModel

_QUESTIONS_PATH = Path(__file__).parent / "meta_questions.json"

AnswerProvider = Union[
    Callable[[str], Awaitable[str]],
    Callable[[str], str],
]


class MetaTurn(BaseModel):
    question_number: int
    question: str
    rationale: str
    answer: str


def _load_questions() -> list[dict]:
    data = json.loads(_QUESTIONS_PATH.read_text(encoding="utf-8"))
    return sorted(data["meta_interview_questions"], key=lambda q: q["number"])


async def run_meta_interview(answer_provider: AnswerProvider) -> list[MetaTurn]:
    """
    Run all 8 meta-interview questions sequentially and return the transcript.

    answer_provider is called once per question; supports sync or async callables.
    """
    turns: list[MetaTurn] = []
    for q in _load_questions():
        raw = answer_provider(q["question"])
        answer: str = await raw if inspect.isawaitable(raw) else raw  # type: ignore[assignment]
        turns.append(
            MetaTurn(
                question_number=q["number"],
                question=q["question"],
                rationale=q.get("rationale", ""),
                answer=answer,
            )
        )
    return turns


def format_transcript(turns: list[MetaTurn]) -> str:
    """Render meta-interview turns as a readable transcript for the LLM."""
    lines: list[str] = []
    for t in turns:
        lines.append(f"Q{t.question_number}: {t.question}")
        lines.append(f"A{t.question_number}: {t.answer}")
        lines.append("")
    return "\n".join(lines).strip()
